#:schema https://json.schemastore.org/ruff.json
extend = ".github/linters/.ruff.toml"

[lint]
extend-ignore = [
  "ARG001",
  "ARG002",
  "B007",
  "E741",
  "F722",
  "N803",
  "N806",
  "N812",
]

[lint.flake8-import-conventions.extend-aliases]
"mkit.math" = "m"
"mkit.typing" = "t"
"mkit.typing.array" = "ta"
"mkit.typing.jax" = "tj"
"mkit.typing.numpy" = "tn"
"mkit.typing.torch" = "tt"
