fix = true
show-fixes = true
target-version = "py311"

[format]
docstring-code-format = true

[lint]
ignore = [
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "D1",
  "E501",
  "ERA",
  "FIX",
  "INP",
  "ISC",
  "N803",
  "N806",
  "PD008",
  "PLR09",
  "PLR2004",
  "RET504",
  "S",
  "T20",
  "TD",
]
select = ["ALL"]

[lint.flake8-import-conventions.extend-aliases]
"jax.numpy" = "jnp"
"jax.typing" = "jxt"
"numpy.typing" = "npt"
"pyvista" = "pv"
"taichi" = "ti"
"trimesh" = "tm"

[lint.pydocstyle]
convention = "google"
