words:
  - amberg
  - arange
  - contourpy
  - cython
  - dicom
  - dmypy
  - dtype
  - envrc
  - gomod
  - imsave
  - ipynb
  - kdtree
  - kron
  - liblaf
  - mdurl
  - mkdocs
  - ndimage
  - nptyping
  - nricp
  - nrrd
  - pybuilder
  - pycache
  - pydantic
  - pyflow
  - pynrrd
  - pypa
  - pypackages
  - pyparsing
  - pytype
  - pyvista
  - qres
  - rclone
  - setaf
  - spsolve
  - toarray
  - tqdm
  - typer
  - voxel
  - vtkmodules
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - golang
  - makefile
  - npm
  - python
  - python-common
allowCompoundWords: true
